access_key = "AKIAVZIODCZZDXYJD24L"
secret_key = "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"
cidr_block = "10.0.0.0/16"
aws_internet_gateway = "green_igw"
public_subnet-1 = "10.0.4.0/24"
public_subnet-2 = "10.0.5.0/24"
route-name = "green_public_route"
security-grp-name = "green-vpc-allow-all"